### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by NitroGhost** [electron/node-rcedit#11] opened 2015-11-15 23:22 UTC
is there a way to change the language code using this? in the resource file there's:

    BLOCK "VarFileInfo"
    {
        VALUE "Translation", 0x0409 0x04B0
    }

where 0x0409 is the English (United States) code

need to change the language to my countries lang

**Comment by kevinsawicki** [comment] 2016-08-18 20:48
This is a duplicate of https://github.com/electron/rcedit/issues/18, closing this out and tracking the issue there.

**Closed by kevinsawicki** 2016-08-18 20:48 UTC
Labels: enhancement
